-- 6. Showcase Items Table
create table if not exists public.showcase_items (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  type text not null, -- 'image' or 'video'
  media_url text not null,
  description text,
  status text default 'published', -- 'published' or 'hidden'
  date date default current_date,
  display_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies (if RLS is enabled, but based on other tables I don't see explicit RLS in the schema file I read, 
-- but I should probably assume the backend handles it or it's public read/admin write)
-- For now, I'll just keep the table definition.
