-- 1. Team Members Table
create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  title text default '',
  bio text default '',
  micro_bio text default '',
  full_bio text default '',
  photo text default '',
  email text default '',
  phone text default '',
  linkedin text default '',
  github text default '',
  twitter text default '',
  responsibilities text[] default '{}',
  tech_stack text[] default '{}',
  projects jsonb default '[]'::jsonb,
  display_order integer default 0,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Projects Table
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  category text not null,
  description text default '',
  image text default '',
  tags text[] default '{}',
  github text default '',
  live_demo text default '',
  featured boolean default false,
  display_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Internships Table
create table if not exists public.internships (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  domain text not null,
  duration text default '',
  price integer default 0,
  description text default '',
  skills text[] default '{}',
  projects text[] default '{}',
  featured boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Messages (Contact Form) Table
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text default '',
  message text not null,
  status text default 'new',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Certificates Table
create table if not exists public.certificates (
  id bigint generated by default as identity primary key,
  student_name text not null,
  internship_title text not null,
  project_title text default '',
  issue_date date default current_date,
  certificate_id text not null unique,
  certificate_file_url text default '',
  profile_photo_url text default '',
  internship_duration text default '',
  start_date date,
  end_date date,
  skills text[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
